const MovieList = [
  {
      "id" : "1",
    "Title": "Inception",
    "slug": "inception",
    "Year": "2010",
    "Rated": "PG-13",
    "Released": "16 Jul 2010",
    "Runtime": "148 min",
    "Genre": "Action, Adventure, Crime",
    "Director": "Christopher Nolan",
    "Writer": "Christopher Nolan",
    "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    "Plot": "A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.",
    "Language": "English, Japanese, French",
    "Country": "USA, UK",
    "Awards": "Won 4 Oscars. Another 143 wins & 198 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    "Metascore": "74",
    "imdbRating": "8.8",
    "imdbVotes": "1,446,708",
    "imdbID": "tt1375666",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://youtu.be/wa1B5M_kBD0?si=1sSvQpufKjGfdG93"
  },
  {
      "id" : "2",
    "Title": "The Shawshank Redemption",
    "Year": "1994",
    slug: "the-shawshank-redemption" ,
    "Rated": "R",
    "Released": "23 Sep 1994",
    "Runtime": "142 min",
    "Genre": "Drama",
    "Director": "Frank Darabont",
    "Writer": "Stephen King, Frank Darabont",
    "Actors": "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    "Plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Nominated for 7 Oscars. Another 16 wins & 30 nominations.",
    "Poster": "https://m.media-amazon.com/images/I/51A3zZer19L._SX300_SY300_QL70_FMwebp_.jpg",
    "Metascore": "80",
    "imdbRating": "9.2",
    "imdbVotes": "1,821,119",
    "imdbID": "tt0111161",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=6hB3S9bIacg"
  },
  {
      "id" : "3",
    "Title": "The Godfather",
    slug: "the-godfather",
    "Year": "1972",
    "Rated": "R",
    "Released": "15 Mar 1972",
    "Runtime": "177 min",
    "Genre": "Crime, Drama",
    "Director": "Francis Ford Coppola",
    "Writer": "Mario Puzo, Francis Ford Coppola",
    "Actors": "Marlon Brando, Al Pacino, James Caan, Robert Duvall",
    "Plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "Language": "English, Italian, Latin",
    "Country": "USA",
    "Awards": "Won 3 Oscars. Another 23 wins & 15 nominations.",
    "Poster": "https://media0050.elcinema.com/uploads/_640x_fbaa3f5faa7b0f15facd2ca8538040725aed35ded9471e41e65a7998dc0ffa47.jpg",
    "Metascore": "100",
    "imdbRating": "9.2",
    "imdbVotes": "1,343,119",
    "imdbID": "tt0068646",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=sY1S34973zA"
  },
    {
      "id" : "4",
    "Title": "The Dark Knight",
    slug: "the-dark-knight" ,
    "Year": "2008",
    "Rated": "PG-13",
    "Released": "18 Jul 2008",
    "Runtime": "162 min",
    "Genre": "Action, Crime, Drama",
    "Director": "Christopher Nolan",
    "Writer": "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    "Actors": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    "Plot": "When the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    "Language": "English, Mandarin",
    "Country": "USA, UK",
    "Awards": "Won 2 Oscars. Another 146 wins & 123 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV2z4tfoQkk5m45inD4FlPkZFTy2a7soTGbw&s",
    "Metascore": "84",
    "imdbRating": "9.0",
    "imdbVotes": "1,823,119",
    "imdbID": "tt0468569",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=_PZpmTjZZQo"
  },
  {
      "id" : "5",
    "Title": "12 Angry Men",
    "Year": "1957",
    slug: "12-angry-men" ,
    "Rated": "Approved",
    "Released": "10 Apr 1957",
    "Runtime": "96 min",
    "Genre": "Drama",
    "Director": "Sidney Lumet",
    "Writer": "Reginald Rose",
    "Actors": "Martin Balsam, E.G. Marshall, Jack Warden, Henry Fonda",
    "Plot": "A jury of 12 men must decide the fate of a young man accused of murder, and the verdict must be unanimous.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Nominated for 3 Oscars. Another 10 wins & 5 nominations.",
    "Poster": "https://upload.wikimedia.org/wikipedia/en/4/44/12_Angry_Men_1997_film_poster.jpg",
    "Metascore": "96",
    "imdbRating": "9.0",
    "imdbVotes": "541,119",
    "imdbID": "tt0050083",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=fRCjpuyrtbQ"
  },
  {
      "id" : "6",
    "Title": "Schindler's List",
    "Year": "1993",
    slug: "schindlers-list",
    "Rated": "R",
    "Released": "15 Dec 1993",
    "Runtime": "195 min",
    "Genre": "Biography, Drama, History",
    "Director": "Steven Spielberg",
    "Writer": "Steven Zaillian",
    "Actors": "Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall",
    "Plot": "In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    "Language": "English, Hebrew, Polish, German",
    "Country": "USA",
    "Awards": "Won 7 Oscars. Another 82 wins & 22 nominations.",
    "Poster": "https://images-cdn.ubuy.co.in/634f9a12ec3ec2031f564253-schindler-39-s-list-movie-art.jpg",
    "Metascore": "97",
    "imdbRating": "8.9",
    "imdbVotes": "1,041,119",
    "imdbID": "tt0108052",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=gEY56i-raya"
  },
    {
      "id" : "7",
    "Title": "The Lord of the Rings: The Return of the King",
    slug: "the-lord-of-the-rings-the-return-of-the-king",
    "Year": "2003",
    "Rated": "PG-13",
    "Released": "17 Dec 2003",
    "Runtime": "201 min",
    "Genre": "Adventure, Drama, Fantasy",
    "Director": "Peter Jackson",
    "Writer": "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    "Actors": "Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom",
    "Plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to save Middle-earth, while Frodo and Samwise Gamgee continue their perilous journey to destroy the One Ring.",
    "Language": "English",
    "Country": "New Zealand, USA",
    "Awards": "Won 11 Oscars. Another 143 wins & 113 nominations.",
    "Poster": "https://images.moviesanywhere.com/45bc0ec075bfc0b4d8f184a7cc5bf993/876ed805-83b1-4387-b0d0-62d08c36536d.webp?h=375&resize=fit&w=250",
    "Metascore": "94",
    "imdbRating": "9.2",
    "imdbVotes": "1,432,119",
    "imdbID": "tt0167260",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=r5X-hFf6Bwo"
  },
  {
      "id" : "8",
    "Title": "Pulp Fiction",
    "Year": "1994",
    "Rated": "R",
    slug: "pulp-fiction",
    "Released": "14 Oct 1994",
    "Runtime": "154 min",
    "Genre": "Crime, Drama",
    "Director": "Quentin Tarantino",
    "Writer": "Quentin Tarantino, Roger Avary",
    "Actors": "John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis",
    "Plot": "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Won 1 Oscar. Another 63 wins & 44 nominations.",
    "Poster": "https://m.media-amazon.com/images/I/81UTs3sC5hL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "Metascore": "94",
    "imdbRating": "9.2",
    "imdbVotes": "1,542,119",
    "imdbID": "tt0110912",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v=s7EdQ4FqbhY"
  },
  { 
      "id" : "9",
    "Title": "The Good, the Bad and the Ugly",
    "Year": "1966",
    "Rated": "R",
    "Released": "29 Dec 1966",
    slug: "the-good-the-bad-and-the-ugly",
    "Runtime": "161 min",
    "Genre": "Western",
    "Director": "Sergio Leone",
    "Writer": "Agenore Incrocci, Furio Scarpelli, Luciano Vincenzoni",
    "Actors": "Clint Eastwood, Lee Van Cleef, Aldo Giuffrè, Luigi Pistilli",
    "Plot": "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
    "Language": "Italian, Spanish",
    "Country": "Italy, Spain, West Germany",
    "Awards": "Nominated for 1 BAFTA Film Award. Another 5 wins & 5 nominations.",
    "Poster": "https://georgetownvoice.com/wp-content/uploads/2016/10/the-good-the-bad-and-the-ugly-il-buono-il-brutto-il-cattivo.9123.jpg",
    "Metascore": "90",
    "imdbRating": "8.8",
    "imdbVotes": "541,119",
    "imdbID": "tt0060196",
    "Type": "movie",
    "Response": "True",
    "Trailer": "https://www.youtube.com/watch?v WC_NtYO331g"

  }
]

export default MovieList;